version: '3'
services:
  backend:
    image: openjdk:11
    build:
      context: ./backend/
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/chatdb"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    image: node:14
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://backend:8080"
