version: '3'
services:
  backend:
    image: openjdk:17
    build:
      context: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/chatdb"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      REACT_APP_BACKEND_URL: "http://backend:8888"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
